# Active rules.  Keep it short.
whitelist_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - convenience_type
  - custom_rules
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - dynamic_inline
  - empty_count
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - identical_operands
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - mark
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_over_fileprivate
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - trailing_semicolon
  - unneeded_break_in_switch
  - weak_delegate
  - closing_brace
  - unowned_variable_capture
  - vertical_whitespace
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment
  - unneeded_parentheses_in_closure_argument
  - trailing_newline
  - trailing_comma
  - redundant_type_annotation
included: # paths to include during linting. `--path` is ignored if present.
  - SentinelDVPN
excluded: # paths to ignore during linting. Takes precedence over `included`.

# Rule configuration.
force_cast:
  severity: warning

force_try:
  severity: warning

line_length: 120

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

custom_rules:
  fixme:
    included: ".*\\.swift"
    name: "FIXME"
    message: "Fix this"
    regex: "\\WFIXME:"
    match_kinds:
      - comment
